CREATE FUNCTION Q6 (@date DATETIME)
RETURNS VARCHAR(10)
AS
BEGIN
	DECLARE @Res AS VARCHAR(10) = DATENAME(day, DATEADD(day, 4, CONVERT(VARCHAR(100), @date)))
	RETURN @Res
END
GO

DECLARE @date DATETIME
SET @date = GETDATE()

DECLARE @Result VARCHAR(10)
EXEC @Result = Q6 @date
PRINT @date
PRINT @Result