USE [master]
GO
/****** Object:  Database [digikala]    Script Date: 7/16/2021 5:29:20 PM ******/
CREATE DATABASE [digikala]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'digikala', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\digikala.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'digikala_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\digikala_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [digikala] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [digikala].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [digikala] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [digikala] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [digikala] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [digikala] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [digikala] SET ARITHABORT OFF 
GO
ALTER DATABASE [digikala] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [digikala] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [digikala] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [digikala] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [digikala] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [digikala] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [digikala] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [digikala] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [digikala] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [digikala] SET  DISABLE_BROKER 
GO
ALTER DATABASE [digikala] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [digikala] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [digikala] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [digikala] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [digikala] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [digikala] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [digikala] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [digikala] SET RECOVERY FULL 
GO
ALTER DATABASE [digikala] SET  MULTI_USER 
GO
ALTER DATABASE [digikala] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [digikala] SET DB_CHAINING OFF 
GO
ALTER DATABASE [digikala] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [digikala] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [digikala] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [digikala] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'digikala', N'ON'
GO
ALTER DATABASE [digikala] SET QUERY_STORE = OFF
GO
USE [digikala]
GO
/****** Object:  Table [dbo].[Comment]    Script Date: 7/16/2021 5:29:20 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Comment](
	[UUId] [bigint] NOT NULL,
	[ProductId] [bigint] NOT NULL,
	[Text] [varchar](1000) NOT NULL,
	[Score] [int] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Customer]    Script Date: 7/16/2021 5:29:20 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customer](
	[UUId] [bigint] IDENTITY(1,1) NOT NULL,
	[UserName] [varchar](256) NOT NULL,
	[Password] [varchar](256) NOT NULL,
	[PhoneNumber] [varchar](11) NOT NULL,
	[Reference] [bigint] NULL,
	[Score] [int] NOT NULL,
 CONSTRAINT [PK_CUSTOMER] PRIMARY KEY CLUSTERED 
(
	[UUId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Discount]    Script Date: 7/16/2021 5:29:20 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Discount](
	[DiscountId] [int] IDENTITY(1,1) NOT NULL,
	[UUId] [bigint] NOT NULL,
	[Code] [varchar](256) NOT NULL,
	[Amount] [int] NOT NULL,
	[IsActive] [bit] NOT NULL,
 CONSTRAINT [PK_DISCOUNT] PRIMARY KEY CLUSTERED 
(
	[DiscountId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Order]    Script Date: 7/16/2021 5:29:20 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Order](
	[OrderId] [bigint] IDENTITY(1,1) NOT NULL,
	[UUId] [bigint] NOT NULL,
	[DiscountId] [int] NULL,
	[TotalPrice] [int] NOT NULL,
	[CreationTime] [datetime] NOT NULL,
	[PaidAmount] [int] NOT NULL,
 CONSTRAINT [PK_ORDER] PRIMARY KEY CLUSTERED 
(
	[OrderId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[OrderItem]    Script Date: 7/16/2021 5:29:20 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OrderItem](
	[ItemId] [bigint] IDENTITY(1,1) NOT NULL,
	[ProductId] [bigint] NOT NULL,
	[OrderId] [bigint] NOT NULL,
	[Fee] [int] NOT NULL,
	[Count] [int] NOT NULL,
 CONSTRAINT [PK_ORDERITEM] PRIMARY KEY CLUSTERED 
(
	[ItemId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Product]    Script Date: 7/16/2021 5:29:20 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Product](
	[ProductId] [bigint] IDENTITY(1,1) NOT NULL,
	[RemainingCount] [int] NOT NULL,
	[Price] [int] NOT NULL,
	[Categoty] [int] NOT NULL,
	[ProductName] [varchar](50) NOT NULL,
 CONSTRAINT [PK_PRODUCT] PRIMARY KEY CLUSTERED 
(
	[ProductId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [Relationship_4_FK]    Script Date: 7/16/2021 5:29:20 PM ******/
CREATE NONCLUSTERED INDEX [Relationship_4_FK] ON [dbo].[Comment]
(
	[UUId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [Relationship_5_FK]    Script Date: 7/16/2021 5:29:20 PM ******/
CREATE NONCLUSTERED INDEX [Relationship_5_FK] ON [dbo].[Comment]
(
	[ProductId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [Relationship_6_FK]    Script Date: 7/16/2021 5:29:20 PM ******/
CREATE NONCLUSTERED INDEX [Relationship_6_FK] ON [dbo].[Discount]
(
	[UUId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [Relationship_1_FK]    Script Date: 7/16/2021 5:29:20 PM ******/
CREATE NONCLUSTERED INDEX [Relationship_1_FK] ON [dbo].[Order]
(
	[UUId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [Relationship_7_FK]    Script Date: 7/16/2021 5:29:20 PM ******/
CREATE NONCLUSTERED INDEX [Relationship_7_FK] ON [dbo].[Order]
(
	[DiscountId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [Relationship_2_FK]    Script Date: 7/16/2021 5:29:20 PM ******/
CREATE NONCLUSTERED INDEX [Relationship_2_FK] ON [dbo].[OrderItem]
(
	[OrderId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Customer] ADD  CONSTRAINT [DF_customer_Score]  DEFAULT ((0)) FOR [Score]
GO
ALTER TABLE [dbo].[Comment]  WITH CHECK ADD  CONSTRAINT [FK_COMMENT_RELATIONS_CUSTOMER] FOREIGN KEY([UUId])
REFERENCES [dbo].[Customer] ([UUId])
GO
ALTER TABLE [dbo].[Comment] CHECK CONSTRAINT [FK_COMMENT_RELATIONS_CUSTOMER]
GO
ALTER TABLE [dbo].[Comment]  WITH CHECK ADD  CONSTRAINT [FK_COMMENT_RELATIONS_PRODUCT] FOREIGN KEY([ProductId])
REFERENCES [dbo].[Product] ([ProductId])
GO
ALTER TABLE [dbo].[Comment] CHECK CONSTRAINT [FK_COMMENT_RELATIONS_PRODUCT]
GO
ALTER TABLE [dbo].[Discount]  WITH CHECK ADD  CONSTRAINT [FK_DISCOUNT_RELATIONS_CUSTOMER] FOREIGN KEY([UUId])
REFERENCES [dbo].[Customer] ([UUId])
GO
ALTER TABLE [dbo].[Discount] CHECK CONSTRAINT [FK_DISCOUNT_RELATIONS_CUSTOMER]
GO
ALTER TABLE [dbo].[Order]  WITH CHECK ADD  CONSTRAINT [FK_ORDER_RELATIONS_CUSTOMER] FOREIGN KEY([UUId])
REFERENCES [dbo].[Customer] ([UUId])
GO
ALTER TABLE [dbo].[Order] CHECK CONSTRAINT [FK_ORDER_RELATIONS_CUSTOMER]
GO
ALTER TABLE [dbo].[Order]  WITH CHECK ADD  CONSTRAINT [FK_ORDER_RELATIONS_DISCOUNT] FOREIGN KEY([DiscountId])
REFERENCES [dbo].[Discount] ([DiscountId])
GO
ALTER TABLE [dbo].[Order] CHECK CONSTRAINT [FK_ORDER_RELATIONS_DISCOUNT]
GO
ALTER TABLE [dbo].[OrderItem]  WITH CHECK ADD  CONSTRAINT [FK_ORDERITE_RELATIONS_ORDER] FOREIGN KEY([OrderId])
REFERENCES [dbo].[Order] ([OrderId])
GO
ALTER TABLE [dbo].[OrderItem] CHECK CONSTRAINT [FK_ORDERITE_RELATIONS_ORDER]
GO
ALTER TABLE [dbo].[OrderItem]  WITH CHECK ADD  CONSTRAINT [FK_ORDERITE_RELATIONS_PRODUCT] FOREIGN KEY([ProductId])
REFERENCES [dbo].[Product] ([ProductId])
GO
ALTER TABLE [dbo].[OrderItem] CHECK CONSTRAINT [FK_ORDERITE_RELATIONS_PRODUCT]
GO
USE [master]
GO
ALTER DATABASE [digikala] SET  READ_WRITE 
GO
